### ISSUE TITLE
Boa sorte

### ISSUE THREAD

**Issue by tiagolobao** [SaitamaXD/Compilador#1]
Essa matéria deve  ser dificil que só a mizera. Vim aqui desejar boa sorte

**Comment by AllanPS98** [comment]
Kkkkkkkk valeu meu guerreiro, mas é tranquila! Sucesso pra ti!

Em dom, 21 de mar de 2021 12:37, Tiago Lobão ***@***.***>
escreveu:

**Comment by tiagolobao** [comment]
Show
